apiVersion: v1
kind: Service
metadata:
  name: micromall-discovery-server
  labels:
    app: micromall-discovery-server
spec:
  selector:
    app: micromall-discovery-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8761     
      targetPort: 8761
      nodePort: 30061

