apiVersion: v1
kind: Service
metadata:
  name: micromall-config-server
  labels:
    app: micromall-config-server
spec:
  selector:
    app: micromall-config-server
  ports:
    - protocol: TCP
      port: 8888     
      targetPort: 8888
      nodePort: 30088
  type: NodePort
