server:
  port: 8761

spring:
  application:
    name: eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, configprops, env
  endpoint:
    health:
      show-details: always


