services:
  mysql:
    container_name: micromall_mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - micromall-net

  keycloak:
    container_name: micromall_keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak_db?createDatabaseIfNotExist=true
      - KC_DB_DRIVER=com.mysql.cj.jdbc.Driver
      - KC_DB_POOL_INITIAL_SIZE=10
      - KC_DB_POOL_MAX_SIZE=100
      - KC_DB_POOL_MIN_SIZE=5
      - KC_DB_SCHEMA=keycloak_db
    ports:
      - "7181:8080"
    depends_on:
      - mysql
    networks:
      - micromall-net

volumes:
  mysql-data:

networks:
  micromall-net:
    driver: bridge
    name: micromall-net