server:
  port: 7081
  servlet:
    context-path: /api

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
    
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.marouanedbibih.studio/realms/micromall
          jwk-set-uri: https://keycloak.marouanedbibih.studio/realms/micromall/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: https://keycloak.marouanedbibih.studio
  realm: micromall
  client-id: admin-cli
  client-secret: Ga13qdc60n3a7soziMAQISfQWEfunWRK

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.micromall: DEBUG
    org.springframework.security: DEBUG