server:
  port: 8081
  
spring:
  application:
    name: catalog-microservice

management:
  endpoints:
    web:
      exposure:
        include: health, info, configprops, env
  endpoint:
    health:
      show-details: always

