spring:
  config:
    import: optional:configserver:http://${CONFIGSERVER_HOST}:${CONFIGSERVER_PORT}
    fail-fast: true
    retry:
      initial-interval: 1500
      multiplier: 1.5
      max-attempts: 10
      max-interval: 10000


