server:
  port: 8091
  
spring:
  application:
    name: catalog-microservice

management:
  endpoints:
    web:
      exposure:
        include: health, info, configprops, env
  endpoint:
    health:
      show-details: always
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: catalog

cors:
  allowed-origins: http://localhost:4200