spring:
  application:
    name: cart-api
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
