spring:
  config:
    activate:
      on-profiles:
        - default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/marouanedbibih/micromall
          default-label: main
          search-paths: system-configurations


