spring:
  config:
    activate:
      on-profiles:
        - docker
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_GIT_URI}
          default-label: main
          search-paths: system-configurations

