server:
  port: 8090 # Port on which the application runs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true 
    username: root # Database username
    password: root # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL Driver (for better compatibility)
  jpa:
    hibernate:
      ddl-auto: update # Update the database schema automatically
    show-sql: true s
    properties:
      hibernate.format_sql: true # Format SQL queries in the logs for better readability
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ 
  instance:
    preferIpAddress: true

logging:
  level:
    root: INFO # Default logging level
    org.springframework: DEBUG # Debug level for Spring Framework
    com.yourcompany.userapi: DEBUG # Debug level for your application's package



